[package]
name = "hibro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ws = "0.9.2"
git2 = "0.17.1"
futures = "0.3.28"
base64 = "0.21.0"
minify-js = "0.5.6"
chrono = "0.4.25"
substring = "1.4.5"
